accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'register/$', views.register_user, name='register_user'),
    url(r'login/$', views.login_user, name='login_user'),
    url(r'logout/$', views.logout_user, name='logout_user'),
    url(r'user/validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate_user,
        name='activate_user'
        )
]

debtinfo/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'debtinfo'

urlpatterns = [
    url(r'^info/search', login_required(views.SearchDebtorListView.as_view()),
        name='search_debtor'),
    url(r'^info/view', login_required(views.ViewDebtorsListView.as_view()),
        name='view_debtors'),
    url(r'^info/download', login_required(views.download_table), name='download_table')
]

remoteref/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^debt/', include('debtinfo.urls')),
    url(r'^$', home, name='home_page')
]

debtinfo/models.py
from django.db import models
from django.conf import settings
from decimal import Decimal
from django.dispatch.dispatcher import receiver
from django.db.models.signals import post_save


class CurrencyField(models.DecimalField):
    """Format value into currency format.

    Inherits from models.DecimalField.
    """

    def __init__(self, *args, **kwargs):
        kwargs['max_digits'] = 11
        kwargs['decimal_places'] = 2
        super(CurrencyField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        try:
            return super(CurrencyField, self).to_python(value).quantize(Decimal('0.01'))
        except AttributeError:
            return None


class Profile(models.Model):
    """A database model of debt information."""

    debtor = models.ForeignKey(settings.AUTH_USER_MODEL, null=False,
                               on_delete=models.CASCADE, related_name='profile_debtor')
    creditor = models.ForeignKey(settings.AUTH_USER_MODEL, null=False,
                                 on_delete=models.CASCADE, related_name='profile_creditor')
    id_number = models.CharField(max_length=10, null=False)
    cell = models.CharField(max_length=12, null=False)
    amount = CurrencyField()

    class Meta:
        db_table = 'tb_profiles'

    def __str__(self):
        return self.debtor.username


class Debtor(models.Model):
    """A database model of a Debtor."""

    debtor = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=False, on_delete=models.CASCADE, related_name='debtor')
    id_number = models.CharField(max_length=10, blank=False)
    cell = models.CharField(max_length=12, blank=False)

    class Meta:
        db_table = 'tbl_due_listing'

    def __str__(self):
        return self.debtor.username


@receiver(post_save, sender=Profile)
def add_debtor(sender, **kwargs):
    """Create a Debtor instance for a created Profile instance."""
    profile = kwargs['instance']

    if kwargs['created']:
        try:
            debtor = Debtor.objects.get(debtor=profile.debtor)
        except Debtor.DoesNotExist:
            debtor = Debtor.objects.create(
                debtor=profile.debtor, id_number=profile.id_number, cell=profile.cell)
        else:
            pass

debtinfo/forms.py
from .models import *
from django import forms


class SearchForm(forms.Form):
    """Configure and return a search form."""

    q = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'validate'}))

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields['q'].label = 'Search'

debtinfo/views.py
from .forms import SearchForm
from .models import Profile, Debtor
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.edit import FormMixin
from django.db.models import Q
from django.template.defaultfilters import pluralize
from django.http import HttpResponse
from django.contrib.auth.decorators import user_passes_test, permission_required
from django.utils.decorators import method_decorator
import re
import openpyxl


class SearchDebtorListView(ListView, FormMixin):
    """A ListView of Debt information together with a search form.

    Inherits from ListView and FormMixin.
    """

    model = Profile
    template_name = 'debtinfo/search_debtor.html'
    context_object_name = 'debtors'
    form_class = SearchForm

    def get_queryset(self):
        """Check if query exists, return objects matching query else return None.

        Override ListView.get_queryset().
        """
        if 'q' in self.request.GET and self.request.GET['q'].strip():
            search_query = self.request.GET['q'].strip()
            field_list = ['id_number', 'cell']
            obj = search_fields(search_query, field_list, model=self.model)
            if obj.count() == 0:
                messages.error(
                    self.request, 'Customer with ID or Contact number "%s" NOT found.' % search_query)
            else:
                result_count = obj.count()
                messages.info(self.request, "{0} {1} found for search '{2}'".format(
                    result_count, counter(result_count, 'result', 'results'), search_query))

        else:
            obj = self.model.objects.none()
            messages.info(
                self.request, 'Search for a Customer by national ID or Contact numbers.')

        return obj

    def get(self, request, *args, **kwargs):
        self.object = None
        self.form = self.get_form(self.form_class)

        return ListView.get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """Validate form data and save to database, return response else return form."""
        self.object = None
        self.form = self.get_form(self.form_class)

        if self.form.is_valid():
            obj = self.form.save(commit=False)
            self.object = obj.save()

            messages.success(request, 'Query successful! ')
            return HttpResponseRedirect(reverse_lazy('debtinfo:search_debtors'))

        return self.get(request, *args, **kwargs)

    def get_success_url(self):
        return HttpResponseRedirect(reverse_lazy('debtinfo:search_debtors'))


class ViewDebtorsListView(ListView):
    """A ListView of Debtor information."""

    model = Debtor
    context_object_name = 'debtors'
    template_name = 'debtinfo/view_debtors.html'

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(ViewDebtorsListView, self).dispatch(request, *args, **kwargs)

@user_passes_test(lambda u: u.is_staff)
def download_table(request):
    """Create Debtors list xlsx file, return download response."""
    debtors = Debtor.objects.all()

    wb = openpyxl.Workbook(write_only=True)
    debtors_sheet = 'Debtors'
    wb.create_sheet(debtors_sheet)
    sheet = wb.get_sheet_by_name(debtors_sheet)
    sheet.append(['First Name', 'Last Name', 'ID', 'Contact'])
    for details in debtors:
        sheet.append([details.debtor.first_name,
                      details.debtor.last_name, details.id_number, details.cell])

    response = HttpResponse(
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=debtors.xlsx'

    wb.save(response)
    wb.close()
    return response


def counter(count, singular, plural):
    """Return the appropriate plural term with regard to the count."""
    return pluralize(count, singular + ',' + plural)


# Search snippet
def search_fields(query_string, field_list, model):
    """Initialise database search of the query provided."""
    entry_query = get_query(query_string, field_list)
    found_entries = model.objects.filter(entry_query)

    return found_entries


def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    """Split query into individual keywords, group quoted words, return list of terms.Example:

    >>> normalize_query('  some random  words "with   quotes  " and   spaces')
    ['some', 'random', 'words', 'with quotes', 'and', 'spaces']

    """
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]


def get_query(query_string, search_fields):
    """ Return a query that is a combination of Q objects. 

    That combination aims to search keywords within a model
    by testing the given search fields.
    """
    query = None  # Query to search for every search term
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None  # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__iexact" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query

debtinfo/templates/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>RemoteRef | {% block page_title %}{% endblock %}</title>

  <link rel="shortcut icon" href="{% static 'icons/favicon.ico' %}">
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>

	<body>
		<nav class="light-blue lighten-1" role="navigation">
		    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'home_page' %}" class="brand-logo">RemoteRef</a>
		      {% if not request.user.is_authenticated %}
		      <ul class="right hide-on-med-and-down">
		        <li><a href="{% url 'accounts:register_user' %}">Register</a></li>
		      </ul>
		      <ul class="right hide-on-med-and-down">
		        <li><a href="{% url 'accounts:login_user' %}">Log in</a></li>
		      </ul>
		      {% else %}
		      <ul class="right hide-on-med-and-down">
		        <li><a href="{% url 'accounts:logout_user' %}">Logout</a></li>
		      </ul>
		      <ul class="right hide-on-med-and-down">
		        <li><a>{{ request.user.username }}</a></li>
		      </ul>
		      <ul class="right hide-on-med-and-down">
		        <li><a href="{% url 'debtinfo:search_debtor' %}">Search Customer</a></li>
		      </ul>
		      {% endif %}
		      {% if request.user.is_staff %}
		      <ul class="right hide-on-med-and-down">
		        <li><a href="{% url 'debtinfo:view_debtors' %}">View Debtors</a></li>
		      </ul>
		      {% endif %}
		    </div>
		</nav>
		<div class="container">
			<br />
			<div class="row">
				<div class="col s12">
					<h4 class="header teal-text darken-4">
						{% block caption %}{% endblock %}
					</h4>
				</div>
			</div>

			{% if messages %}
			<div class="section">
				<ul class="collection">
				{% for message in messages %}
					<li class="collection-item {{ message.tags }}">{{ message }}</li>
				{% endfor %}
				</ul>
			</div>
			{% endif %}

			<div class="section">
			{% block content %}{% endblock %}
			</div>
		</div>

		<div class="footer">
			<div class="footer-copyright">
		      <div class="container center">
		      Copyright &copy; 2017 <a class="orange-text text-lighten-3" href="https://github.com/giantas">Aswa Paul</a>
		      &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
		      Theme by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
		      </div>
		    </div>
		</div>

		{% block javascript %}{% endblock %}

		<!--  Scripts-->
		<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script src="{% static 'js/materialize.js' %}"></script>
		<script src="{% static 'js/init.js' %}"></script>

	</body>

</html>

debtinfo/templates/home_page.html
{% extends 'base.html' %}

{% block page_title %}Home{% endblock %}

{% block content %}

	<div class="container">
      <h1 class="header center orange-text">RemoteRef</h1>
      <div class="row center">
        <h5 class="header col s12 light">
        	A remote reference application based on Material Design
        </h5>
      </div>
      <div class="row center">
        <div class="card z-depth-0">
		    <div class="card-content">
		      <p>Check customer debt information remotely.</p>
		    </div>
		    <div class="card-tabs">
		      <ul class="tabs tabs-fixed-width">
		        <li class="tab"><a href="#test4">Search Customer</a></li>
		        {% if request.user.is_staff %}
		        <li class="tab"><a class="active" href="#test5">View Debtors</a></li>
		        {% endif %}
		      </ul>
		    </div>
		    <div class="card-content grey lighten-4">
		      <div id="test4">
		      	<a href="{% url 'debtinfo:search_debtor' %}">Look up</a> customer debt information by national ID or mobile number.
		      </div>
		      {% if request.user.is_staff %}
		      <div id="test5">
		      	<a href="{% url 'debtinfo:view_debtors' %}">View</a> and download debtors list.
		      </div>
		      {% endif %}
		    </div>
		</div>

      </div>
      <br><br>

    </div>

{% endblock %}